version: '3.9'

services:

  db:
    image: postgres:14.5
    container_name: db
    environment:
      - POSTGRES_HOST:${POSTGRES_HOST}
      - POSTGRES_DB:${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - .env
    ports:
      - 5432:5432

  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - db

  nginx:
    build:
      context: ./proxy
    restart: always
    container_name: app_nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app
    ports:
      - 80:80

volumes:
  static_volume:
  media_volume:
  db_data:
