version: '3.9'

services:

  dbp:
    image: postgres:14-alpine
    container_name: dbp
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    restart: always
    env_file:
      - .env
    ports:
      - 5432:5432

  app_main:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8000
    restart: always
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env
    ports:
      - 8000:8000
    depends_on:
      - dbp

  nginx:
    build:
      context: ./proxy
    restart: always
    container_name: app_nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    depends_on:
      - app_main
      - dbp
    ports:
      - 80:80

volumes:
  static_volume:
  media_volume:
