version: '3.9'

services:

  db:
    image: postgres:14.5
    container_name: db
    restart: always
    volumes:
      - .data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=simple_blog
      - POSTGRES_USER=postgres
      - postgres_PASSWORD=postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - "5432:5432"

  app:
    container_name: app
    build:
      dockerfile: ./Dockerfile
    command:
      - gunicorn
      - mysite.wsgi:application
      - --bind
      - 0.0.0.0:8000
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    depends_on:
      - db